# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - apis/poi

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: dotnet build apis/poi/poi.sln  --configuration Release
  displayName: 'Build'

- script: dotnet test apis/poi/tests/UnitTests --logger trx
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'